TALK_TO_FILE_GEMINI:
  model: gemini-1.5-pro-preview-0409
  temperature: 0.5
  max_output_tokens: 8192
  top_p: 1.0
  stop_sequences: ["<END>"]

TALK_TO_FILE_CHITCHAT_GEMINI:
  model: gemini-1.5-pro-preview-0409
  temperature: 0.5
  max_output_tokens: 256
  top_p: 1.0
  stop_sequences: ["<END>"]
 