TALK_TO_FILE_CHITCHAT:
  model: gpt-4-turbo
  temperature: 0.5
  max_tokens: 256
  top_p: 1.0
  frequency_penalty: 0.0
  presence_penalty: 0.0
  stop_sequences: ["<END>"]

GET_ANTHROPIC_ANSWER:
  model: claude-3-sonnet-20240229
  max_tokens: 400
  temperature: 0.0
  stop_sequences: ["<END>"]

TALK_TO_MULTIPLE_FILES:
  model: gpt-4-turbo
  temperature: 0.5
  max_tokens: 1500
  top_p: 1.0
  frequency_penalty: 0.0
  presence_penalty: 0.0
  stop_sequences: ["<END>"]
 